### NEW ACCOUNTT
POST http://localhost:4000/api/accounts/
Content-Type: application/json

{
  "id": "navalny"
}

### LIST ACCOUNTS
POST http://localhost:4000/api/accounts/list/
Content-Type: application/json

{
  "accounts": [ "44196397"]
}

### RETRIEVE

GET http://localhost:4000/api/accounts/44196397/
Content-Type: application/json

